error: 

    ┌── tests/move_check/typing/module_call_internal.move:4:5 ───
    │
 10 │         X::foo()
    │         ^^^^^^^^ Invalid call to '0x1::X::foo'
    ·
 4 │     foo() {}
    │     --- This function is internal to its module. Only 'public' functions can be called outside of their module
    │

